# Name of the Workflow

name: Deploy Timer App

# Controls when the action will run.
on:
  push:
    branches: [ forSurgeUrl ]
  pull_request:
    branches: [ forSurgeUrl ]

# Define Jobs
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Node JS
      - name: Install Nodejs
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      
      # Install Yarn
      - name: Install Yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
    
      # Buold React APP
      - name: Build React App
        run: yarn build
      
      # Install Surge
      - name: Install Surge
        run: npm install -g surge
      
      # Run Surge
      - name: Run surge
        run: surge ./build http://project07b-hassanalikhan.surge.sh/ --token ${{secrets.surge_token}}